# Generated by Django 5.2.3 on 2026-02-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('strorganizativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strorganizativa.unidadorganizativa'),
        ),
    ]
