# Generated by Django 5.2.3 on 2026-08-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_notificacion_destinatario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['severidad', '-fecha_creado'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='clave_extra',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='codigo_regla',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activa'), ('RES', 'Resuelta'), ('DES', 'Descartada')], default='ACT', max_length=3),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='severidad',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Crítica'), (20, 'Alta'), (30, 'Media'), (40, 'Baja'), (50, 'Informativa')], null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('EVE', 'Evento'), ('ALE', 'Alerta'), ('SIS', 'Sistema'), ('REC', 'Recordatorio')], default='EVE', max_length=3),
        ),
    ]
