# Generated by Django 5.2.3 on 2026-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0006_reclasificar_criticas'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='campo_formulario',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
