# Generated by Django 5.2.3 on 2026-08-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0007_notificacion_campo_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fecha_objetivo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='origen',
            field=models.CharField(blank=True, choices=[('SIS', 'Sistema'), ('ADM', 'Administración')], default='', max_length=3),
        ),
    ]
