# Generated by Django 5.2.3 on 2026-04-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cant_aprobada', models.IntegerField()),
                ('cant_cubierta', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('puesto_clave', models.BooleanField(default=False, verbose_name='Puesto Clave')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizativa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_interno', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Interno')),
                ('grupo_nomina', models.IntegerField(blank=True, null=True, verbose_name='Grupo de Nómina')),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Unidad Organizativa',
                'verbose_name_plural': 'Unidades Organizativas',
            },
        ),
    ]
