# Generated by Django 5.2.3 on 2026-02-02 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '0002_initial'),
        ('strorganizativa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoplantilla',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargoplantilla',
            name='ncargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nomencladores.ncargo', verbose_name='Nomenclador de Cargo'),
        ),
        migrations.AddField(
            model_name='cargoplantilla',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='nomencladores.nrol', verbose_name='Nomenclador de Rol'),
        ),
        migrations.AddField(
            model_name='cargoplantilla',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargoplantilla',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='strorganizativa.departamento'),
        ),
        migrations.AddField(
            model_name='unidadorganizativa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidadorganizativa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidad_organizativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='strorganizativa.unidadorganizativa'),
        ),
    ]
