# Generated by Django 5.2.3 on 2026-06-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strorganizativa', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoplantilla',
            name='puesto_clave',
        ),
    ]
