# Generated by Django 5.2.3 on 2026-04-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strorganizativa', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadorganizativa',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_hijas', to='strorganizativa.unidadorganizativa', verbose_name='Pertenece a'),
        ),
    ]
