# Generated by Django 5.2.3 on 2026-06-24 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strorganizativa', '0003_remove_cargoplantilla_puesto_clave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['orden_informe', 'descripcion'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='unidadorganizativa',
            options={'ordering': ['orden_informe', 'descripcion'], 'verbose_name': 'Unidad Organizativa', 'verbose_name_plural': 'Unidades Organizativas'},
        ),
        migrations.AddField(
            model_name='departamento',
            name='orden_informe',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Posición dentro de la Unidad'),
        ),
        migrations.AddField(
            model_name='unidadorganizativa',
            name='orden_informe',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Posición en el Organigrama'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='unidad_organizativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departamentos', to='strorganizativa.unidadorganizativa'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('unidad_organizativa', 'orden_informe'), name='unique_orden_depto_por_unidad'),
        ),
    ]
