# Generated by Django 5.2.3 on 2026-07-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strorganizativa', '0004_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoplantilla',
            name='designado',
            field=models.BooleanField(default=False, verbose_name='Designado'),
        ),
        migrations.AddField(
            model_name='cargoplantilla',
            name='funcionario',
            field=models.BooleanField(default=False, verbose_name='Funcionario'),
        ),
    ]
