# Generated by Django 5.2.3 on 2026-07-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strorganizativa', '0005_cargoplantilla_designado_cargoplantilla_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['orden_informe', 'id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='orden_informe',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Posición dentro de la Unidad'),
        ),
    ]
