# Generated by Django 5.2.3 on 2026-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strorganizativa', '0006_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargoplantilla',
            options={'ordering': ['orden_informe', 'ncargo__descripcion'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AddField(
            model_name='cargoplantilla',
            name='orden_informe',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orden de prioridad'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='orden_informe',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Posición dentro de la Unidad'),
        ),
    ]
