# Generated by Django 5.2.3 on 2026-07-16 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0005_nnocturnidad_ncondicionlaboralanormal_nocturnidad'),
        ('strorganizativa', '0007_alter_cargoplantilla_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cargoplantilla',
            constraint=models.UniqueConstraint(fields=('departamento', 'orden_informe'), name='unique_orden_cargo_por_departamento'),
        ),
    ]
