# Generated by Django 5.2.3 on 2026-07-23 18:41

import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strorganizativa', '0008_cargoplantilla_unique_orden_cargo_por_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departamento',
            name='unique_orden_depto_por_unidad',
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('unidad_organizativa', 'orden_informe'), name='unique_orden_depto_por_unidad'),
        ),
    ]
