# Generated by Django 5.2.3 on 2026-07-23 19:45

import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0005_nnocturnidad_ncondicionlaboralanormal_nocturnidad'),
        ('strorganizativa', '0009_remove_departamento_unique_orden_depto_por_unidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cargoplantilla',
            name='unique_orden_cargo_por_departamento',
        ),
        migrations.AddConstraint(
            model_name='cargoplantilla',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('departamento', 'orden_informe'), name='unique_orden_cargo_por_departamento'),
        ),
    ]
