# Generated by Django 5.2.3 on 2026-07-24 13:56

import django.db.models.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0005_nnocturnidad_ncondicionlaboralanormal_nocturnidad'),
        ('strorganizativa', '0010_remove_cargoplantilla_unique_orden_cargo_por_departamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadorganizativa',
            name='orden_informe',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Posición en el Organigrama'),
        ),
        migrations.AddConstraint(
            model_name='unidadorganizativa',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('padre', 'orden_informe'), name='unique_orden_por_rama', nulls_distinct=False),
        ),
    ]
