# Generated by Django 5.2.3 on 2026-07-28 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0011_poblar_valor_numerico_grupos'),
        ('strorganizativa', '0011_alter_unidadorganizativa_orden_informe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadorganizativa',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomencladores.nmunicipio', verbose_name='Municipio'),
        ),
    ]
