# Generated by Django 5.2.3 on 2025-09-09 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('org_superior', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_presup', models.BooleanField(default=False)),
                ('rama', models.CharField(blank=True, max_length=50, null=True)),
                ('moneda_local', models.CharField(default='CUP', max_length=10)),
                ('periodo', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(7)])),
                ('fondo_tiempo_calc_tarif', models.DecimalField(decimal_places=2, default=190.6, max_digits=5)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/empr/')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
