# Generated by Django 5.2.3 on 2026-07-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_initial'),
        ('nomencladores', '0005_nnocturnidad_ncondicionlaboralanormal_nocturnidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='provincia_entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomencladores.nprovincia', verbose_name='Provincia de la Entidad'),
        ),
    ]
