# Generated by Django 5.2.3 on 2026-07-28 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configuracion_provincia_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='reup',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El REUP solo puede contener números y guiones (-).', regex='^[0-9-]*$')], verbose_name='REUP'),
        ),
    ]
