# Generated by Django 5.2.3 on 2026-07-28 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformePersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del informe')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('modelo_raiz', models.CharField(max_length=50, verbose_name='Modelo base')),
                ('configuracion', models.JSONField(help_text='Campos, filtros, agrupación y orden elegidos por el usuario.', verbose_name='Configuración del informe')),
                ('es_plantilla', models.BooleanField(default=False, help_text='Las plantillas las ve cualquier usuario; los informes propios solo su dueño.', verbose_name='Es plantilla del sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Vacío si es una plantilla del sistema, disponible para todos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informes_personalizados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Informe Personalizado',
                'verbose_name_plural': 'Informes Personalizados',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='UltimoInformeEjecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_raiz', models.CharField(max_length=50)),
                ('configuracion', models.JSONField()),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('fecha_ejecucion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ultimo_informe_ejecutado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Último Informe Ejecutado',
                'verbose_name_plural': 'Últimos Informes Ejecutados',
            },
        ),
        migrations.CreateModel(
            name='InformeFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_favoritos', to=settings.AUTH_USER_MODEL)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcado_como_favorito_por', to='informe_inteligente.informepersonalizado')),
            ],
            options={
                'verbose_name': 'Informe Favorito',
                'verbose_name_plural': 'Informes Favoritos',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'informe')},
            },
        ),
    ]
