# Generated by Django 5.2.3 on 2026-06-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMensualRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=2)),
                ('anno', models.CharField(max_length=4)),
                ('ueb_id', models.CharField(blank=True, max_length=10, null=True)),
                ('familia_id', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('mes', 'anno', 'ueb_id', 'familia_id')},
            },
        ),
    ]
