# Generated by Django 5.2.3 on 2026-07-31 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('strorganizativa', '0013_alter_unidadorganizativa_unique_orden_por_rama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CUR', 'En curso'), ('COM', 'Completa'), ('PAR', 'Parcial'), ('FAL', 'Fallida')], default='CUR', max_length=3, verbose_name='Estado')),
                ('origen', models.CharField(choices=[('MAN', 'Manual (desde la interfaz)'), ('CMD', 'Comando de consola'), ('PRG', 'Programada')], default='MAN', max_length=3, verbose_name='Origen')),
                ('iniciada_en', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada')),
                ('terminada_en', models.DateTimeField(blank=True, null=True, verbose_name='Terminada')),
                ('duracion_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (ms)')),
                ('modulos_solicitados', models.JSONField(blank=True, default=list)),
                ('modulos_completados', models.JSONField(blank=True, default=list)),
                ('reglas_ejecutadas', models.PositiveSmallIntegerField(default=0)),
                ('modelos_analizados', models.JSONField(blank=True, default=list)),
                ('registros_analizados', models.PositiveIntegerField(default=0, help_text='Filas distintas revisadas, contando cada modelo una sola vez.', verbose_name='Registros analizados')),
                ('errores', models.JSONField(blank=True, default=dict)),
                ('hallazgos_nuevos', models.PositiveIntegerField(default=0)),
                ('hallazgos_persistentes', models.PositiveIntegerField(default=0)),
                ('hallazgos_resueltos', models.PositiveIntegerField(default=0)),
                ('hallazgos_vigentes', models.PositiveIntegerField(default=0)),
                ('indice_salud', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Índice de salud (%)')),
                ('version_indice', models.PositiveSmallIntegerField(default=1)),
                ('lanzada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_lanzados', to=settings.AUTH_USER_MODEL, verbose_name='Lanzada por')),
            ],
            options={
                'verbose_name': 'Ejecución de análisis',
                'verbose_name_plural': 'Ejecuciones de análisis',
                'ordering': ['-iniciada_en'],
            },
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_regla', models.CharField(help_text='Estable para siempre: es parte de la clave natural del hallazgo.', max_length=20, verbose_name='Código de la regla')),
                ('object_id', models.CharField(blank=True, default='', help_text='Vacío cuando el hallazgo es global y no apunta a una fila concreta.', max_length=50, verbose_name='Registro afectado')),
                ('clave_extra', models.CharField(blank=True, default='', help_text='Discrimina varios hallazgos de la misma regla sobre el mismo registro.', max_length=50)),
                ('modulo', models.CharField(choices=[('contratos', 'Contratos'), ('nomina', 'Nómina e Históricos'), ('aspirantes', 'Aspirantes'), ('usuarios', 'Usuarios'), ('estructura', 'Plantilla y Estructura'), ('ocultos', 'Ocultos'), ('calidad', 'Calidad de datos'), ('configuracion', 'Configuración')], max_length=20, verbose_name='Categoría')),
                ('criticidad', models.PositiveSmallIntegerField(choices=[(10, 'Crítica'), (20, 'Alta'), (30, 'Media'), (40, 'Baja'), (50, 'Informativa')], verbose_name='Criticidad')),
                ('titulo', models.CharField(help_text='Debe incluir los datos buscables del registro (nombre, CI, expediente).', max_length=255, verbose_name='Título')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('datos', models.JSONField(blank=True, default=dict, verbose_name='Datos del hallazgo')),
                ('huella', models.CharField(blank=True, default='', max_length=32)),
                ('vigente', models.BooleanField(default=True, help_text='False cuando el último análisis ya no lo detectó.', verbose_name='Vigente')),
                ('primera_deteccion', models.DateTimeField(auto_now_add=True)),
                ('ultima_deteccion', models.DateTimeField()),
                ('veces_detectado', models.PositiveIntegerField(default=1)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelto_automaticamente', models.BooleanField(default=False, help_text='True cuando dejó de detectarse, no cuando una persona lo cerró.')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('REV', 'En revisión'), ('COR', 'Corregido'), ('IGN', 'Ignorado'), ('FAL', 'Falso positivo')], default='PEN', max_length=3, verbose_name='Estado')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos_subsanacion', to='contenttypes.contenttype', verbose_name='Tipo de registro')),
                ('ejecucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos', to='subsanacion.ejecucionanalisis', verbose_name='Detectado en')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('unidad_organizativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos_subsanacion', to='strorganizativa.unidadorganizativa', verbose_name='Unidad organizativa')),
            ],
            options={
                'verbose_name': 'Hallazgo',
                'verbose_name_plural': 'Hallazgos',
                'ordering': ['criticidad', '-ultima_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='RevisionHallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PEN', 'Pendiente'), ('REV', 'En revisión'), ('COR', 'Corregido'), ('IGN', 'Ignorado'), ('FAL', 'Falso positivo')], max_length=3)),
                ('estado_nuevo', models.CharField(choices=[('PEN', 'Pendiente'), ('REV', 'En revisión'), ('COR', 'Corregido'), ('IGN', 'Ignorado'), ('FAL', 'Falso positivo')], max_length=3)),
                ('nota', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('automatica', models.BooleanField(default=False, help_text='True cuando la transición la hizo el motor, no una persona.', verbose_name='Automática')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='subsanacion.hallazgo', verbose_name='Hallazgo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_hallazgo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Revisión de hallazgo',
                'verbose_name_plural': 'Revisiones de hallazgos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='ejecucionanalisis',
            index=models.Index(fields=['-iniciada_en'], name='subs_ejec_fecha_desc'),
        ),
        migrations.AddConstraint(
            model_name='ejecucionanalisis',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CUR')), fields=('estado',), name='subs_una_ejecucion_en_curso'),
        ),
        migrations.AddIndex(
            model_name='hallazgo',
            index=models.Index(condition=models.Q(('vigente', True)), fields=['criticidad', '-ultima_deteccion'], name='subs_hall_vigentes_crit'),
        ),
        migrations.AddIndex(
            model_name='hallazgo',
            index=models.Index(condition=models.Q(('vigente', True)), fields=['modulo', 'estado'], name='subs_hall_modulo_estado'),
        ),
        migrations.AddIndex(
            model_name='hallazgo',
            index=models.Index(condition=models.Q(('vigente', True)), fields=['unidad_organizativa', 'criticidad'], name='subs_hall_uo_crit'),
        ),
        migrations.AddIndex(
            model_name='hallazgo',
            index=models.Index(fields=['codigo_regla', 'vigente'], name='subs_hall_regla_vig'),
        ),
        migrations.AddConstraint(
            model_name='hallazgo',
            constraint=models.UniqueConstraint(fields=('codigo_regla', 'content_type', 'object_id', 'clave_extra'), name='subs_hallazgo_clave_natural'),
        ),
        migrations.AddIndex(
            model_name='revisionhallazgo',
            index=models.Index(fields=['hallazgo', '-fecha'], name='subs_revision_hallazgo'),
        ),
    ]
