# Generated by Django 5.2.3 on 2026-08-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsanacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionanalisis',
            name='registros_por_modulo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
