# Generated by Django 5.2.3 on 2026-08-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsanacion', '0002_ejecucionanalisis_registros_por_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionanalisis',
            name='version_indice',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
