# Generated by Django 5.2.3 on 2026-08-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsanacion', '0003_alter_ejecucionanalisis_version_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionanalisis',
            name='codigos_regla_ejecutados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
