# Generated by Django 5.2.3 on 2025-10-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contratos', '0003_initial'),
        ('strorganizativa', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('es_admin', True), ('es_moderador', True), _negated=True), name='roles_exclusivos_admin_xor_moderador'),
        ),
    ]
