# Generated by Django 5.2.3 on 2026-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contratos', '0009_alter_calta_cnci'),
        ('strorganizativa', '0005_cargoplantilla_designado_cargoplantilla_funcionario'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='roles_exclusivos_admin_xor_moderador',
        ),
        migrations.AddField(
            model_name='customuser',
            name='es_observador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('es_admin', True), ('es_moderador', False), ('es_observador', False)), models.Q(('es_admin', False), ('es_moderador', True), ('es_observador', False)), models.Q(('es_admin', False), ('es_moderador', False), ('es_observador', True)), _connector='OR'), name='exactamente_un_rol'),
        ),
    ]
