# Generated by Django 5.2.3 on 2026-07-30 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_roles_exclusivos_admin_xor_moderador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/avatares/', verbose_name='Foto de perfil'),
        ),
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_colapsada', models.BooleanField(default=False, verbose_name='Barra lateral colapsada por defecto')),
                ('animaciones_activas', models.BooleanField(default=True, verbose_name='Animaciones de la interfaz activas')),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencias de usuario',
                'verbose_name_plural': 'Preferencias de usuarios',
            },
        ),
    ]
