# Generated by Django 5.2.3 on 2025-09-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ADD', 'Creacion'), ('DEL', 'Eliminar'), ('UPD', 'Modificar')], max_length=3)),
                ('estado', models.CharField(choices=[('E', 'Enviada'), ('R', 'En Revision'), ('A', 'Aprobada'), ('X', 'Rechazada')], default='E', max_length=1)),
                ('motivo', models.TextField()),
                ('fecha_vigor', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_vigor'],
            },
        ),
    ]
