# Generated by Django 5.2.3 on 2025-09-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('strorganizativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcargo',
            name='cargo_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='strorganizativa.cargoplantilla'),
        ),
    ]
