# Generated by Django 5.2.3 on 2026-07-30 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Descripción del problema')),
                ('url_origen', models.CharField(blank=True, max_length=255, verbose_name='Página desde la que se reportó')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('ATE', 'Atendido'), ('DES', 'Descartado')], default='PEN', max_length=3, verbose_name='Estado')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reporte')),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_problema', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Reporte de problema',
                'verbose_name_plural': 'Reportes de problemas',
                'ordering': ['-fecha_creado'],
            },
        ),
    ]
