# Generated by Django 5.2.3 on 2026-07-30 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteproblema',
            name='error_consola',
            field=models.TextField(blank=True, help_text='Texto exacto del error mostrado en la consola del navegador, si el usuario lo vio.', verbose_name='Error de consola (F12)'),
        ),
        migrations.CreateModel(
            name='ImagenReporteProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img/reportes/', verbose_name='Imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='soporte.reporteproblema', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Imagen de reporte',
                'verbose_name_plural': 'Imágenes de reportes',
            },
        ),
    ]
