# Generated by Django 5.2.3 on 2026-04-23 14:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('cat_ocupacional', models.CharField(choices=[('TEC', 'Técnico'), ('ADM', 'Administrativo'), ('SER', 'Servicio'), ('OPE', 'Operario'), ('CDI', 'Cuadro Directivo'), ('CEJ', 'Cuadro Ejecutivo')], max_length=20)),
                ('salario_basico', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'NCargo',
                'verbose_name_plural': 'NCargos',
            },
        ),
        migrations.CreateModel(
            name='NCausaAltaBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('alta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'NCausa Alta/Baja',
                'verbose_name_plural': 'NCausas de Alta/Baja',
            },
        ),
        migrations.CreateModel(
            name='NCondicionLaboralAnormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Condición Laboral Anormal',
                'verbose_name_plural': 'Condiciones Laborales Anormales',
            },
        ),
        migrations.CreateModel(
            name='NEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('educ_superior', models.BooleanField(default=False, verbose_name='Educ. Superior')),
            ],
            options={
                'verbose_name': 'NEspecialidad',
                'verbose_name_plural': 'NEspecialidad',
            },
        ),
        migrations.CreateModel(
            name='NFamiliaCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Familia de Cargos',
                'verbose_name_plural': 'Familias de Cargos',
            },
        ),
        migrations.CreateModel(
            name='NGrupoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel', models.CharField(max_length=8, unique=True)),
                ('es_cuadro', models.BooleanField(default=False, verbose_name='Es Cuadro')),
                ('tiene_rol', models.BooleanField(default=True, verbose_name='Tiene Rol')),
            ],
            options={
                'verbose_name': 'NGrupoEscala',
                'verbose_name_plural': 'NGruposEscalas',
            },
        ),
        migrations.CreateModel(
            name='NHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NHorario',
                'verbose_name_plural': 'NHorarios',
            },
        ),
        migrations.CreateModel(
            name='NJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'NJornada',
                'verbose_name_plural': 'NJornadas',
            },
        ),
        migrations.CreateModel(
            name='NMotivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Motivo de Contrato',
                'verbose_name_plural': 'Motivos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='NMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'NMunicipio',
                'verbose_name_plural': 'NMunicipios',
            },
        ),
        migrations.CreateModel(
            name='NNivelPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Nivel de Preparación',
                'verbose_name_plural': 'Niveles de Preparación',
            },
        ),
        migrations.CreateModel(
            name='NProvincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'NProvincia',
                'verbose_name_plural': 'NProvincias',
            },
        ),
        migrations.CreateModel(
            name='NRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'NRol',
                'verbose_name_plural': 'NRoles',
            },
        ),
        migrations.CreateModel(
            name='NSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'NSalario',
                'verbose_name_plural': 'NSalarios',
            },
        ),
        migrations.CreateModel(
            name='NTipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
                ('ocupa_plaza', models.BooleanField(default=False, verbose_name='¿Ocupa Plaza en Plantilla?')),
                ('requiere_motivo', models.BooleanField(default=False, verbose_name='¿Requiere Motivo?')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contratos',
            },
        ),
        migrations.CreateModel(
            name='NTipoFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Familia')),
            ],
            options={
                'verbose_name': 'Tipo de Familia',
                'verbose_name_plural': 'Tipos de Familias',
            },
        ),
        migrations.CreateModel(
            name='NTipoUnidadOrganizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=150, unique=True, verbose_name='Tipo de Unidad')),
                ('es_temporal', models.BooleanField(default=False, verbose_name='Es temporal')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Unidad Principal')),
                ('es_subunidad', models.BooleanField(default=False, verbose_name='Subunidad')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color de Jerarquía')),
            ],
            options={
                'verbose_name': 'Tipo de Unidad Organizativa',
                'verbose_name_plural': 'Tipos de Unidades Organizativas',
            },
        ),
        migrations.CreateModel(
            name='NTridente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'NTridente',
                'verbose_name_plural': 'NTridentes',
            },
        ),
    ]
