# Generated by Django 5.2.3 on 2026-06-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncargo',
            name='puesto_clave',
            field=models.BooleanField(default=False, verbose_name='Puesto Clave'),
        ),
    ]
