# Generated by Django 5.2.3 on 2026-04-10 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncargo',
            name='familia',
        ),
        migrations.AddField(
            model_name='ncargo',
            name='familias',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='nomencladores.nfamiliacargo'),
        ),
        migrations.CreateModel(
            name='NTipoFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Familia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Familia',
                'verbose_name_plural': 'Tipos de Familias',
            },
        ),
        migrations.AddField(
            model_name='nfamiliacargo',
            name='tipo_familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='familias', to='nomencladores.ntipofamilia'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='nfamiliacargo',
            unique_together={('nombre', 'tipo_familia')},
        ),
    ]
