# Generated by Django 5.2.3 on 2026-02-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0003_nfamiliacargo_ncargo_familia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncargo',
            name='activo',
        ),
    ]
