# Generated by Django 5.2.3 on 2026-06-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0003_ncargo_puesto_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmotivocontrato',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='motivos', to='nomencladores.ntipocontrato', verbose_name='Tipo de Contrato Asociado'),
        ),
        migrations.AddField(
            model_name='ntipocontrato',
            name='es_adiestrado',
            field=models.BooleanField(default=False, verbose_name='¿Es Adiest?'),
        ),
    ]
