# Generated by Django 5.2.3 on 2026-02-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0004_remove_ncargo_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngrupoescala',
            name='es_cuadro',
        ),
        migrations.AddField(
            model_name='nrol',
            name='es_cuadro',
            field=models.BooleanField(default=False, verbose_name='Es Cuadro'),
        ),
    ]
