# Generated by Django 5.2.3 on 2026-07-25 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0005_nnocturnidad_ncondicionlaboralanormal_nocturnidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmotivocontrato',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AddConstraint(
            model_name='nmotivocontrato',
            constraint=models.UniqueConstraint(fields=('descripcion', 'tipo_contrato'), name='unique_motivo_por_tipo', nulls_distinct=False),
        ),
    ]
