# Generated by Django 5.2.3 on 2026-07-25 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0006_alter_nmotivocontrato_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nmotivocontrato',
            name='unique_motivo_por_tipo',
        ),
        migrations.AlterField(
            model_name='nmotivocontrato',
            name='tipo_contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='motivos', to='nomencladores.ntipocontrato', verbose_name='Tipo de Contrato Asociado'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='nmotivocontrato',
            constraint=models.UniqueConstraint(fields=('descripcion', 'tipo_contrato'), name='unique_motivo_por_tipo'),
        ),
    ]
