# Generated by Django 5.2.3 on 2026-07-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0007_remove_nmotivocontrato_unique_motivo_por_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmunicipio',
            name='siglas',
            field=models.CharField(blank=True, help_text='Exactamente 3 letras mayúsculas', max_length=3, null=True, verbose_name='Siglas'),
        ),
        migrations.AddField(
            model_name='nprovincia',
            name='siglas',
            field=models.CharField(blank=True, help_text='Exactamente 3 letras mayúsculas', max_length=3, null=True, verbose_name='Siglas'),
        ),
    ]
