# Generated by Django 5.2.3 on 2026-07-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0008_nmunicipio_siglas_nprovincia_siglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncargo',
            name='cat_ocupacional',
            field=models.CharField(choices=[('TEC', 'Técnico'), ('ADM', 'Administrativo'), ('SER', 'Servicio'), ('OPE', 'Obrero'), ('CDI', 'Cuadro Directivo'), ('CEJ', 'Cuadro Ejecutivo')], max_length=20),
        ),
    ]
