# Generated by Django 5.2.3 on 2026-07-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0009_alter_ncargo_cat_ocupacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngrupoescala',
            name='valor_numerico_db',
            field=models.IntegerField(default=999, editable=False, verbose_name='Valor numérico (orden)'),
        ),
    ]
