# Generated by Django 5.2.3 on 2025-09-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_identidad', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('papellido', models.CharField(max_length=30)),
                ('sapellido', models.CharField(max_length=30)),
                ('movil_personal', models.CharField(blank=True, max_length=8, null=True)),
                ('fijo_personal', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('nota_adicional', models.TextField(blank=True, null=True)),
                ('raza', models.CharField(blank=True, choices=[('BL', 'Blanca'), ('NE', 'Negra'), ('ME', 'Mestiza')], max_length=50, null=True)),
                ('grado_cientifico', models.CharField(blank=True, choices=[('MC', 'Master'), ('DC', 'Doctor')], max_length=50, null=True)),
                ('nivel_educ', models.CharField(blank=True, choices=[('PR', 'Primaria'), ('NG', 'Medio'), ('MS', 'Medio Superior (DG)'), ('TM', 'Medio Superior (TM)'), ('NS', 'Nivel Superior'), ('OC', 'Obrero Calificado'), ('SA', 'Sin Acreditar')], max_length=50, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('contratado', models.BooleanField(blank=True, default=False, null=True)),
                ('tpantalon', models.CharField(blank=True, max_length=5, null=True)),
                ('tcamisa', models.CharField(blank=True, max_length=5, null=True)),
                ('tzapatos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
            },
        ),
    ]
