# Generated by Django 5.2.3 on 2026-02-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_identidad', models.CharField(max_length=11, unique=True, verbose_name='Carnet de Identidad')),
                ('nombre', models.CharField(max_length=20)),
                ('papellido', models.CharField(max_length=30)),
                ('sapellido', models.CharField(max_length=30)),
                ('movil_personal', models.CharField(blank=True, max_length=15, null=True)),
                ('fijo_personal', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('nota_adicional', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ASPIRANTE', 'Aspirante'), ('ACTIVO', 'Activo'), ('BAJA', 'Baja')], default='ASPIRANTE', max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('raza', models.CharField(blank=True, choices=[('BL', 'Blanca'), ('NE', 'Negra'), ('ME', 'Mestiza')], max_length=50, null=True)),
                ('grado_cientifico', models.CharField(blank=True, choices=[('MC', 'Master'), ('DC', 'Doctor')], max_length=50, null=True)),
                ('nivel_educ', models.CharField(blank=True, choices=[('SA', 'Sin Acreditar'), ('PR', 'Primaria'), ('NG', 'Medio'), ('OC', 'Obrero Calificado'), ('TM', 'Medio Superior (TM)'), ('MS', 'Medio Superior (DG)'), ('NS', 'Nivel Superior')], max_length=50, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('contratado', models.BooleanField(blank=True, default=False, null=True)),
                ('tpantalon', models.CharField(blank=True, max_length=5, null=True)),
                ('tcamisa', models.CharField(blank=True, max_length=5, null=True)),
                ('tzapatos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aspirante',
                'verbose_name_plural': 'Aspirantes',
            },
        ),
    ]
