# Generated by Django 5.2.3 on 2026-02-02 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolsa', '0001_initial'),
        ('nomencladores', '0001_initial'),
        ('strorganizativa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='nomencladores.nespecialidad'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nomencladores.nmunicipio'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nomencladores.nprovincia'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='unidad_organizativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='strorganizativa.unidadorganizativa'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
