# Generated by Django 5.2.3 on 2025-10-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_initial'),
        ('strorganizativa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='unidad_organizativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='strorganizativa.unidadorganizativa'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='contratado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
