# Generated by Django 5.2.3 on 2026-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='titulo_oro',
            field=models.BooleanField(default=False, verbose_name='Título de Oro'),
        ),
    ]
