# Generated by Django 5.2.3 on 2026-06-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0003_aspirante_titulo_oro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='habilidades',
        ),
    ]
