# Generated by Django 5.2.3 on 2025-10-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0003_aspirante_unidad_organizativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='contratado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
