# Generated by Django 5.2.3 on 2025-11-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0004_alter_aspirante_contratado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='nivel_educ',
            field=models.CharField(blank=True, choices=[('SA', 'Sin Acreditar'), ('PR', 'Primaria'), ('NG', 'Medio'), ('OC', 'Obrero Calificado'), ('TM', 'Medio Superior (TM)'), ('MS', 'Medio Superior (DG)'), ('NS', 'Nivel Superior')], max_length=50, null=True),
        ),
    ]
