# Generated by Django 5.2.3 on 2026-07-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0004_remove_aspirante_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, editable=False, help_text='Calculada automáticamente desde el Carnet de Identidad.', null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
