# Generated by Django 5.2.3 on 2025-11-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0005_alter_aspirante_nivel_educ'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='estado',
            field=models.CharField(choices=[('ASPIRANTE', 'Aspirante'), ('ACTIVO', 'Activo'), ('BAJA', 'Baja')], default='ASPIRANTE', max_length=20),
        ),
    ]
