# Generated by Django 5.2.3 on 2025-12-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0006_aspirante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='movil_personal',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
