# Generated by Django 5.2.3 on 2026-08-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0006_poblar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='contratado',
        ),
    ]
