# Generated by Django 5.2.3 on 2025-12-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0007_alter_aspirante_movil_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
