# Generated by Django 5.2.3 on 2026-04-06 23:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_militar', models.TextField(blank=True, choices=[('MTT', 'MTT'), ('IMP', 'Imprescindible'), ('BPD', 'BPD'), ('NIN', 'No Incorporado')], max_length=3, null=True)),
                ('profesional', models.BooleanField(default=False)),
                ('no_expediente', models.CharField(max_length=5)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('cobro_sistema_pago', models.BooleanField(default=False, verbose_name='¿Cobró sistema de pago?')),
            ],
            options={
                'verbose_name': 'Baja',
                'verbose_name_plural': 'Bajas',
            },
        ),
        migrations.CreateModel(
            name='TMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_expediente', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_movimiento', models.DateField(auto_now_add=True)),
                ('fecha_efectiva', models.DateField()),
                ('cargo_anterior', models.CharField(max_length=255)),
                ('cargo_nuevo', models.CharField(max_length=255)),
                ('salario_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_nueva', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_movimiento', models.CharField(default='Movimiento de Nómina', max_length=50)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha de Solicitud')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_efectiva'],
            },
        ),
        migrations.CreateModel(
            name='CAlta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_expediente', models.CharField(max_length=5, unique=True, verbose_name='No. Expediente')),
                ('reg_militar', models.TextField(blank=True, choices=[('MTT', 'MTT'), ('IMP', 'Imprescindible'), ('BPD', 'BPD'), ('NIN', 'No Incorporado')], max_length=3, null=True)),
                ('profesional', models.BooleanField(default=False)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('c_formal', models.BooleanField(default=False)),
                ('funcionario', models.BooleanField(default=False)),
                ('designado', models.BooleanField(default=False)),
                ('c_formal_res', models.TextField(blank=True, max_length=7, null=True)),
                ('funcionario_res', models.TextField(blank=True, max_length=7, null=True)),
                ('designado_res', models.TextField(blank=True, max_length=7, null=True)),
                ('tipo_salario', models.CharField(choices=[('FIJ', 'Fijo'), ('DIN', 'Dinámico')], default='DIN', max_length=3)),
                ('maestria', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('doctorado', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cnci', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('instructor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla1', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla3', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla4', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla5', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_vence_lic', models.DateField(blank=True, null=True)),
                ('fecha_vence_recal', models.DateField(blank=True, null=True)),
                ('fecha_vence_seg', models.DateField(blank=True, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('jubilado_recontratado', models.BooleanField(default=False)),
                ('en_proceso_movimiento', models.BooleanField(default=False, verbose_name='En Proceso de Movimiento')),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_contratos', to='bolsa.aspirante')),
            ],
            options={
                'verbose_name': 'Alta',
                'verbose_name_plural': 'Altas',
            },
        ),
    ]
