# Generated by Django 5.2.3 on 2025-09-09 18:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBaja',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_expediente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('IND', 'Indeterminado'), ('DET', 'Determinado'), ('EAD', 'En Adiestramiento'), ('MOT', 'Movimiento Temporal')], max_length=50)),
                ('reg_militar', models.TextField(blank=True, choices=[('MTT', 'MTT'), ('IMP', 'Imprescindible'), ('BPD', 'BPD'), ('NIN', 'No Incorporado')], max_length=3, null=True)),
                ('profesional', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Baja',
                'verbose_name_plural': 'Bajas',
            },
        ),
        migrations.CreateModel(
            name='CAlta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_expediente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('IND', 'Indeterminado'), ('DET', 'Determinado'), ('EAD', 'En Adiestramiento'), ('MOT', 'Movimiento Temporal')], max_length=50)),
                ('reg_militar', models.TextField(blank=True, choices=[('MTT', 'MTT'), ('IMP', 'Imprescindible'), ('BPD', 'BPD'), ('NIN', 'No Incorporado')], max_length=3, null=True)),
                ('profesional', models.BooleanField(default=False)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('c_formal', models.BooleanField(default=False)),
                ('funcionario', models.BooleanField(default=False)),
                ('designado', models.BooleanField(default=False)),
                ('c_formal_res', models.TextField(blank=True, max_length=7, null=True)),
                ('funcionario_res', models.TextField(blank=True, max_length=7, null=True)),
                ('designado_res', models.TextField(blank=True, max_length=7, null=True)),
                ('tipo_salario', models.CharField(choices=[('FIJ', 'Fijo'), ('DIN', 'Dinámico')], default='DIN', max_length=3)),
                ('maestria', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('doctorado', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cnci', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('instructor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cla5', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_vence_lic', models.DateField(blank=True, null=True)),
                ('fecha_vence_recal', models.DateField(blank=True, null=True)),
                ('fecha_vence_seg', models.DateField(blank=True, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bolsa.aspirante')),
            ],
            options={
                'verbose_name': 'Alta',
                'verbose_name_plural': 'Altas',
            },
        ),
    ]
