# Generated by Django 5.2.3 on 2025-09-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('strorganizativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calta',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='strorganizativa.cargoplantilla'),
        ),
    ]
