# Generated by Django 5.2.3 on 2026-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbaja',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de la Baja'),
        ),
    ]
