# Generated by Django 5.2.3 on 2025-11-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calta',
            name='jubilado_recontratado',
            field=models.BooleanField(default=False),
        ),
    ]
