# Generated by Django 5.2.3 on 2026-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbaja',
            name='actividad_realizada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actividad que realizaba'),
        ),
    ]
