# Generated by Django 5.2.3 on 2026-02-02 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateField(auto_now_add=True)),
                ('fecha_efectiva', models.DateField()),
                ('cargo_anterior', models.CharField(max_length=255)),
                ('cargo_nuevo', models.CharField(max_length=255)),
                ('salario_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_movimiento', models.CharField(default='Movimiento de Nómina', max_length=50)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidad', to='contratos.calta')),
            ],
            options={
                'ordering': ['-fecha_efectiva'],
            },
        ),
    ]
