# Generated by Django 5.2.3 on 2026-04-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_cbaja_actividad_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbaja',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de documento'),
        ),
    ]
