# Generated by Django 5.2.3 on 2026-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_cbaja_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmovimiento',
            name='tridente_nuevo',
        ),
        migrations.AddField(
            model_name='tmovimiento',
            name='duracion_nueva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmovimiento',
            name='motivo_anterior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tmovimiento',
            name='motivo_nuevo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tmovimiento',
            name='tipo_contrato_anterior',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tmovimiento',
            name='tipo_contrato_nuevo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
