# Generated by Django 5.2.3 on 2026-02-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_tmovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmovimiento',
            name='unidad_anterior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tmovimiento',
            name='unidad_nueva',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
