# Generated by Django 5.2.3 on 2026-01-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_calta_jubilado_recontratado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calta',
            name='en_proceso_movimiento',
            field=models.BooleanField(default=False, verbose_name='En Proceso de Movimiento'),
        ),
    ]
