# Generated by Django 5.2.3 on 2026-02-02 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_initial'),
        ('contratos', '0005_tmovimiento_unidad_anterior_tmovimiento_unidad_nueva'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmovimiento',
            name='aspirante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bolsa.aspirante'),
        ),
        migrations.AddField(
            model_name='tmovimiento',
            name='no_expediente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tmovimiento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazabilidad', to='contratos.calta'),
        ),
    ]
