# Generated by Django 5.2.3 on 2026-07-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_remove_tmovimiento_tridente_nuevo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmovimiento',
            name='tridente_nuevo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
