# Generated by Django 5.2.3 on 2026-02-01 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_calta_en_proceso_movimiento'),
        ('nomencladores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbaja',
            name='causa_baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='nomencladores.ncausaaltabaja'),
        ),
        migrations.AddField(
            model_name='cbaja',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cbaja',
            name='tridente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='nomencladores.ntridente'),
        ),
    ]
