# Generated by Django 5.2.3 on 2026-07-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_tmovimiento_tridente_nuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calta',
            name='designado',
        ),
        migrations.RemoveField(
            model_name='calta',
            name='funcionario',
        ),
    ]
