# Generated by Django 5.2.3 on 2026-02-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_tmovimiento_aspirante_tmovimiento_no_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbaja',
            name='no_expediente',
            field=models.CharField(max_length=5),
        ),
    ]
