# Generated by Django 5.2.3 on 2026-07-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_remove_calta_designado_remove_calta_funcionario'),
        ('nomencladores', '0005_nnocturnidad_ncondicionlaboralanormal_nocturnidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calta',
            name='cla1',
        ),
        migrations.RemoveField(
            model_name='calta',
            name='cla2',
        ),
        migrations.RemoveField(
            model_name='calta',
            name='cla3',
        ),
        migrations.RemoveField(
            model_name='calta',
            name='cla4',
        ),
        migrations.RemoveField(
            model_name='calta',
            name='cla5',
        ),
        migrations.AddField(
            model_name='calta',
            name='cla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contratos_cla', to='nomencladores.ncondicionlaboralanormal', verbose_name='Condición Laboral Anormal (CLA)'),
        ),
        migrations.AddField(
            model_name='calta',
            name='nocturnidad_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contratos_noct1', to='nomencladores.ncondicionlaboralanormal', verbose_name='Nocturnidad 1'),
        ),
        migrations.AddField(
            model_name='calta',
            name='nocturnidad_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contratos_noct2', to='nomencladores.ncondicionlaboralanormal', verbose_name='Nocturnidad 2'),
        ),
    ]
