# Generated by Django 5.2.3 on 2026-02-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_cbaja_no_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmovimiento',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Solicitud'),
        ),
        migrations.AddField(
            model_name='tmovimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
