# Generated by Django 5.2.3 on 2026-07-13 18:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_remove_calta_cla1_remove_calta_cla2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calta',
            name='cnci',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
