# Generated by Django 5.2.3 on 2026-02-05 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_tmovimiento_fecha_solicitud_and_more'),
        ('nomencladores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calta',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='nomencladores.nrol', verbose_name='Rol de Pago'),
        ),
    ]
