# Generated by Django 5.2.3 on 2026-07-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_alter_calta_cnci'),
    ]

    operations = [
        migrations.AddField(
            model_name='calta',
            name='salario_actual',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Se recalcula automáticamente en cada guardado. No editar a mano.', max_digits=10, null=True, verbose_name='Salario actual (calculado)'),
        ),
    ]
