# Generated by Django 5.2.3 on 2026-07-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_calta_salario_actual'),
        ('strorganizativa', '0013_alter_unidadorganizativa_unique_orden_por_rama'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmovimiento',
            name='unidad_anterior_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strorganizativa.unidadorganizativa', verbose_name='Unidad Anterior (relación)'),
        ),
        migrations.AddField(
            model_name='tmovimiento',
            name='unidad_nueva_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strorganizativa.unidadorganizativa', verbose_name='Unidad Nueva (relación)'),
        ),
    ]
