# Generated by Django 5.2.3 on 2026-08-03 13:57
#
# Evidencia de EXPLAIN ANALYZE que justifica este índice (Fase 4 del plan de
# Subsanación): sirve al `partition_by=[aspirante_id]` + `order_by=[fecha_efectiva,
# id]` que usa la regla MOV-001 (subsanacion/reglas/nomina.py) para comprobar la
# continuidad del histórico salarial con una función de ventana `Lag()`.
#
# Con las 109 filas de la base de desarrollo, el planificador de PostgreSQL elige
# correctamente `Seq Scan` + `Sort` en memoria (es más barato para una tabla tan
# pequeña) tanto antes como después de crear el índice: el índice no cambia el plan
# a este volumen, y eso es lo esperable, no un fallo.
#
# Para comprobar que el índice SÍ sirve a la consulta (y no solo que existe), se
# forzó al planificador con `SET LOCAL enable_seqscan = off` dentro de una
# transacción real. Con el índice, el `WindowAgg` pasa a leer directamente de
# `Index Scan using contratos_tmov_asp_fecha_id` y el `Sort` interno de la partición
# (`Sort Key: aspirante_id, fecha_efectiva, id`) desaparece por completo del plan;
# sin el índice, ese `Sort` en memoria era el primer nodo bajo el `WindowAgg` incluso
# forzando el mismo ajuste. Queda un `Sort` externo por `-fecha_efectiva` (el
# `ORDER BY` de la vista de contratos), que es un problema distinto y no lo resuelve
# este índice.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0007_remove_aspirante_contratado'),
        ('contratos', '0011_tmovimiento_unidad_anterior_fk_and_more'),
        ('strorganizativa', '0013_alter_unidadorganizativa_unique_orden_por_rama'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tmovimiento',
            index=models.Index(fields=['aspirante', 'fecha_efectiva', 'id'], name='contratos_tmov_asp_fecha_id'),
        ),
    ]
